### ISSUE TITLE
acceptance or submit should also be support enter key press

### ISSUE THREAD

**Issue by radhe-zeeve** [Zeeve-App/larch#138]
In dialog boxes or forms in the application should support enter key press to submit / accept the inputs.

https://github.com/w3f/Grant-Milestone-Delivery/pull/868#pullrequestreview-1529239252

**Comment by ThaungThanHan** [comment]
Hello @radhe-zeeve. I would like to work on this. Please assign it to me.

**Comment by BirmaAlfred** [comment]
Hello @radhe-zeeve, I would be glad to  help with this problem.

**Comment by takahser** [comment]
Still doesn't work on the "create network" dialog:

<img width="1193" alt="image" src="https://github.com/Zeeve-App/larch/assets/5393704/21ea2b6f-8882-42e1-955f-64e072ea5e6b">
